backend:
  name: git-gateway
  repo: rdjarbeng/bugudon-gatsby
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img"


collections:
  - label: "Home Page"
    name: "content"
    files:
      - label: "Home Page Carousel top (sliding images)"
        name: "homepage carousel"
        file: "src/content/homeCarousel.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "images"}
          - {label: "Image One", name: "image1", widget: "image", default: "ghana.png"}
          - {label: "Image Two", name: "image2", widget: "image", default: "ghana.png"}
          - {label: "Image Three", name: "image3", widget: "image", default: "ghana.png"}
          - {label: "Vision under images", name: "vision", widget: "string"}
      
  - label: "Homepage Projects section" # Used in the UI
    name: "HomepageProjects" # Used in routes, e.g., /admin/collections/blog
    folder: "src/content/HomeProjects" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Read More text", name: "readMoreText", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  # - name: "HomepageInvestors" # Used in routes, e.g., /admin/collections/blog
  #   label: "Homepage Investor section" # Used in the UI
  #   folder: "src/pagecontent/HomeInvestors" # The path to the folder where the documents are stored
  #   create: false # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Help Text", name: "helpText", widget: "string"}
  #     - {label: "Image", name: "image", widget: "image", default: "ghana.png"}
  #     - {label: "Body", name: "body", widget: "markdown"}